### ISSUE TITLE
Log file needs to report which version of the Podo program was used.

### ISSUE THREAD

**Issue by GenevieveBuckley** [monashmicroimaging/podocytes#27]
Log file needs to report which version of the Podo program was used.

Instead of this:

```
2018-08-31 11:13:22,261 Podocyte automated analysis program
```
We want to have this:

```
2018-08-31 11:13:22,261 Podocyte automated analysis program v0.1.1-alpha
```

**Comment by jni** [comment]
It's also possible (using e.g. `versioneer`, although I think SciPy has its own much more lightweight scheme) to include the start of the git hash, so you don't need to make a new release every time you change something and want to ship.

**Comment by GenevieveBuckley** [comment]
Now the version number is also reported in the Podo GUI description when you open the app :)
