### ISSUE TITLE
Create _version.py file to track version numbers of podo, loci_tools.jar, etc. in a central place

### ISSUE THREAD

**Issue by GenevieveBuckley** [monashmicroimaging/podocytes#32]
Nice to have, not crucial: auto update to latest loci_tools.jar bioformats version (currently the version number is hard coded).

Both pims and Juan's changes to the Podo.spec file in https://github.com/monashmicroimaging/podocytes/pull/31 rely on a hard coded version number for loci_tools.jar But, bioformats updates pretty regularly (see http://downloads.openmicroscopy.org/bio-formats/) so it would be nice if it checked we're using the latest version every time the app gets built.

**Comment by jni** [comment]
Well, being on the latest always is a double-edged sword. I prefer that we update at our own pace, in case the latest breaks things.

**Comment by GenevieveBuckley** [comment]
Reasonable plan, so long as we remember this has to be incremented manually. I should make a _version.py file to contain this info somewhere people will see it. Might be the best of both worlds that way.

**Comment by GenevieveBuckley** [comment]
Remember that the `Podo.spec` file currently has the loci_tools.jar version number hard-coded in it.
