### ISSUE TITLE
Podo executable icon left in Mac taskbar after Gooey window is closed

### ISSUE THREAD

**Issue by GenevieveBuckley** [monashmicroimaging/podocytes#6]
The Podo executable leaves its icon hanging around in the Mac taskbar (Mac OS High Sierra 10.13.4), even after the program has run to completion and Gooey window has been closed. 

It's not causing any problems that I can tell, but it's also not exactly preferred behaviour.

<img width="342" alt="screen shot 2018-05-24 at 9 25 41 am" src="https://user-images.githubusercontent.com/30920819/40520567-3bba4796-600a-11e8-95c4-0240bfe24665.png">

**Comment by GenevieveBuckley** [comment]
I did not observe this behaviour with a build using pims, so when [this pull](https://github.com/monashmicroimaging/podocytes/pull/7) I'll close out the issue.

**Comment by jni** [comment]
Aaaaah I remember now that if you don’t manually kill the VM, the process just hangs when Python tries to exit! Solution: add lifio.done() at the end of the process!

**Comment by jni** [comment]
Ideally this would be automated via some context manager magic but we can leave that till later. It’s not trivial because you can’t restart the VM once you’ve killed it...

**Comment by GenevieveBuckley** [comment]
Now that pull https://github.com/monashmicroimaging/podocytes/pull/7 is merged into master, we don't see this behaviour anymore.
